### ISSUE TITLE
Bug: for some reason the route to search books is not returning the ids

### ISSUE THREAD

**Issue by misalima** [misalima/book-finder-backend#29]
**Description:**
The route `app/book/search/:title` send books in the response, but without the book `id`. The task is to find out why and fix it so it sends the `id` as well. 

![image](https://github.com/user-attachments/assets/7c5b6a76-4b37-4c38-9444-4fbc1f3e1160)

**Comment by efraimmf** [comment]
The problem is within the createBook method. As it is currently implemented, the book ID is not included in the JSON response. 

![Captura de tela 2024-09-01 234353](https://github.com/user-attachments/assets/5c65bab0-6fce-4387-8ecd-a628a073a133)
![image](https://github.com/user-attachments/assets/e1c7383c-8aea-4201-b7a0-d83bf7811c48)


The ID is only returned after the record has been created in the local database.

![image](https://github.com/user-attachments/assets/03c646eb-8f2a-43a4-9e21-645a46058302)
